[build]
builder = "nixpacks"
buildCommand = "gem install bundler:2.1.4 && bundle install"

[deploy]
startCommand = "bundle exec rails server -b 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
